[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/unite.vim'
on_ft = ['python','cpp']

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = '''
 autocmd FileType python setlocal completeopt-=preview
 let g:jedi#popup_on_dot = 0
'''
[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = 'cpp'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

#[[plugins]]
#repo = 'andviro/flake8-vim'
#on_ft = 'python'

[[plugins]]
repo = "nathanaelkane/vim-indent-guides"
on_ft = ['python','cpp']

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['python','cpp']

[[plugins]]
repo = 'Shougo/context_filetype.vim'
on_ft = ['python','cpp']

[[plugins]]
repo = "Shougo/neocomplete.vim"
depends    = ['neoinclude.vim', 'context_filetype.vim']
insert     = 1
on_ft = ['python','cpp']

[[plugins]]
repo = 'ervandew/supertab'
hook_add = '''
let g:SuperTabDefaultCompletionType = "<c-n>"
'''
on_ft = ['python','cpp']
